baseURL = "https://nfwyst.js.org"
languageCode = "en-us"
pagination.pagerSize = 5
title = "nfwyst's blog"
theme = "re-terminal"

[taxonomies]
tag = "tags"
keyword = "keywords"

[params]
contentTypeName = "posts"
themeColor = "blue"
showMenuItems = 2
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = true
Toc = true
TocTitle = "Outline"
readingTime = false

[params.twitter]
creator = "qi_wo58048"
site = "https://x.com/qi_wo58048"

[languages]
[languages.en.params]
title = "A shortcut is the longest distance between two points"
subtitle = ""
owner = ""
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"

[languages.en.params.logo]
logoText = "A shortcut is the longest distance between two points"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "关于"
url = "/about"
